trigger:
- main 

pool:
  name: 'Default'

steps:
- task: AzureWebAppContainer@1
  inputs:
    azureSubscription: 'azmi' 
    appName: 'azmiWebapp' 
    imageName: 'azmicontainer.azurecr.io/myapp'  
    tag: 'latest'  
