trigger:
- main 

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureWebAppContainer@1
  inputs:
    azureSubscription: 'Azure for Students' 
    appName: 'chiragwebapp' 
    containers: 'chiragregistry.azurecr.io/hello-world:latest'