trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: '<Azure for Students>'
  containerRegistry: '<chiragregistry>.azurecr.io'
  imageName: 'my-app'

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - task: Docker@2
            displayName: 'Build and Push Image'
            inputs:
              containerRegistry: '$(azureSubscription)'
              repository: '$(chiragregistry)/$(imageName)'
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'
              tags: |
                latest

  - stage: Deploy
    dependsOn: Build
    jobs:
      - deployment: Deploy
        environment: 'production'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureWebAppContainer@1
                  displayName: 'Deploy to Azure Web App'
                  inputs:
                    azureSubscription: '$(Azure for Students)'
                    appName: '<chiragwebapp>'
                    imageName: '$(chiragregistry)/$(imageName):latest'
