trigger:
- main 

pool:
  name: 'Default'

steps:
- task: AzureWebAppContainer@1
  inputs:
    azureSubscription: 'Azure for Students' 
    appName: 'chiragwebapp' 
    imageName: 'chiragregistry.azurecr.io/hello-world'  
    tag: 'latest'  
